# Generated by scripts/update-packages.sh on every release.
class Whoport < Formula
  desc "See which project is running on which port, then stop it"
  homepage "https://github.com/vqorn/whoport"
  version "1.2.3"
  license "MIT"

  on_macos do
    url "https://github.com/vqorn/whoport/releases/download/v1.2.3/whoport-macos-universal.tar.gz"
    sha256 "2cf14f2947375d0b0201c19b8b3fc64787a8a47d73bf91d3230f85349ceb2efc"
  end

  on_linux do
    on_intel do
      url "https://github.com/vqorn/whoport/releases/download/v1.2.3/whoport-linux-x86_64.tar.gz"
      sha256 "66f86d89cd376399ac4db18f8862cee3a463776ec88ba81081a0103ca5b01d23"
    end
    on_arm do
      url "https://github.com/vqorn/whoport/releases/download/v1.2.3/whoport-linux-arm64.tar.gz"
      sha256 "8d4040186da7be02d7ea28a57dde70ca984a022015de8b2b705f6c70ebd39098"
    end
  end

  def install
    bin.install "whoport"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whoport --version")
  end
end
