# Generated by scripts/update-packages.sh on every release.
class Whoport < Formula
  desc "See which project is running on which port, then stop it"
  homepage "https://github.com/vqorn/whoport"
  version "1.2.1"
  license "MIT"

  on_macos do
    url "https://github.com/vqorn/whoport/releases/download/v1.2.1/whoport-macos-universal.tar.gz"
    sha256 "135c9dd1216413ae2b16df0beb716c3c5920bfaf3d02ee88ce0790091ac93a89"
  end

  on_linux do
    on_intel do
      url "https://github.com/vqorn/whoport/releases/download/v1.2.1/whoport-linux-x86_64.tar.gz"
      sha256 "1dd226ccb37525d4d129afaf4e4c13f855fa7205cf9f871c65045661e8b9d75f"
    end
    on_arm do
      url "https://github.com/vqorn/whoport/releases/download/v1.2.1/whoport-linux-arm64.tar.gz"
      sha256 "4951b54c0dc65440d850f88178ce7a366c5cc5b8b8ba4b0b05cb20093e71dc44"
    end
  end

  def install
    bin.install "whoport"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whoport --version")
  end
end
