#!/bin/sh
# Writes the Scoop manifest and the Homebrew formula for a release.
# Usage: scripts/update-packages.sh <version> <dir with the release archives>
set -eu

VERSION=$1
DIR=$2
BASE="https://github.com/vqorn/whoport/releases/download/v$VERSION"
ROOT=$(cd "$(dirname "$0")/.." && pwd)

sha() {
    if command -v sha256sum >/dev/null 2>&1; then sha256sum "$DIR/$1" | cut -d' ' -f1
    else shasum -a 256 "$DIR/$1" | cut -d' ' -f1; fi
}

WIN=$(sha whoport-windows-x86_64.zip)
MAC=$(sha whoport-macos-universal.tar.gz)
LINUX_X64=$(sha whoport-linux-x86_64.tar.gz)
LINUX_ARM=$(sha whoport-linux-arm64.tar.gz)

cat > "$ROOT/bucket/whoport.json" <<JSON
{
    "version": "$VERSION",
    "description": "See which project is running on which port. Then stop it.",
    "homepage": "https://github.com/vqorn/whoport",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "$BASE/whoport-windows-x86_64.zip",
            "hash": "$WIN"
        }
    },
    "bin": "whoport.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/vqorn/whoport/releases/download/v\$version/whoport-windows-x86_64.zip"
            }
        }
    }
}
JSON

cat > "$ROOT/Formula/whoport.rb" <<RUBY
# Generated by scripts/update-packages.sh on every release.
class Whoport < Formula
  desc "See which project is running on which port, then stop it"
  homepage "https://github.com/vqorn/whoport"
  version "$VERSION"
  license "MIT"

  on_macos do
    url "$BASE/whoport-macos-universal.tar.gz"
    sha256 "$MAC"
  end

  on_linux do
    on_intel do
      url "$BASE/whoport-linux-x86_64.tar.gz"
      sha256 "$LINUX_X64"
    end
    on_arm do
      url "$BASE/whoport-linux-arm64.tar.gz"
      sha256 "$LINUX_ARM"
    end
  end

  def install
    bin.install "whoport"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whoport --version")
  end
end
RUBY

echo "Updated bucket/whoport.json and Formula/whoport.rb for $VERSION"
